export enum ApplicationCommands {
    CREATELAYER = "CREATELAYER",
    REFRESHLAYERS = "REFRESHLAYERS",
    MAPSAVESTATUS = "MAPSAVESTATUS",
    MAPRESTORE = "MAPRESTORE",
    WORKSPACERESTORE = "WORKSPACERESTORE",
    WORKSPACESAVE = "WORKSPACESAVE",
    APPTOAST = "APPTOAST",
    WORKSPACENEW = "WORKSPACENEW",
    MAPRESET = "MAPRESET",
    APPALERT = "APPALERT",
    CREATE_APP_FORM = "CREATE_APP_FORM",
    TOGGLE_FULL_SCREEN = "TOGGLE_FULL_SCREEN",
}

